---
# tasks file for EffectiveDevOps-node-helloworld
- name: Copy application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644

- name: Copy upstart file
  copy:
    src: helloworld.upstart
    dest: /etc/init/helloworld.conf
    owner: root
    group: root
    mode: 0644

- name: Start Hello World node service
  service:
    name: helloworld
    state: started
